### ISSUE TITLE
XSum dataset in python2

### ISSUE THREAD

**Issue by shivajid** [GoogleCloudPlatform/t5x-on-vertex-ai#4]
The XSum dataset download is on python2. It would be good to have a python3 version as notebooks are on python3

**Comment by leiterenato** [comment]
Hi @shivajid,
Unfortunately we don't control how the XSUM data is downloaded. The scripts are provided by another open source project.
https://github.com/EdinburghNLP/XSum/blob/master/XSum-Dataset/README.md#running-the-download-and-extraction-scripts

Please let me know if you are having any issues downloading this dataset.
Thank you!
